/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.water.client.views;

import java.awt.Color;

/**
 *
 * @author SL_WOLF
 */
public class Check_Stats extends javax.swing.JPanel {

    /**
     * Creates new form Manage_Services
     */
    public Check_Stats() {
        initComponents();
        Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStats = new javax.swing.JLabel();
        lblBar = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(846, 639));
        setMinimumSize(new java.awt.Dimension(846, 639));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStats.setBackground(new java.awt.Color(255, 102, 51));
        lblStats.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStats.setForeground(new java.awt.Color(255, 255, 255));
        lblStats.setText("        +  Check Customer Stats");
        lblStats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblStats.setOpaque(true);
        lblStats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatsMouseClicked(evt);
            }
        });
        add(lblStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        lblBar.setBackground(new java.awt.Color(255, 102, 51));
        lblBar.setOpaque(true);
        add(lblBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void lblStatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatsMouseClicked
        lblStats.setForeground(Color.BLACK);
        lblStats.setBackground(Color.WHITE);
        

         pnlMain.setVisible(true);
         Check_Customer_Stats check_Customer_Stats = new Check_Customer_Stats();
        pnlMain.removeAll();
        check_Customer_Stats.setSize(pnlMain.getSize());
        pnlMain.add(check_Customer_Stats);
        pnlMain.repaint();
        pnlMain.revalidate();
    }//GEN-LAST:event_lblStatsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBar;
    private javax.swing.JLabel lblStats;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    private void Load() {
        lblStats.setForeground(Color.BLACK);
        lblStats.setBackground(Color.WHITE);
        

         pnlMain.setVisible(true);
         Check_Customer_Stats check_Customer_Stats = new Check_Customer_Stats();
        pnlMain.removeAll();
        check_Customer_Stats.setSize(pnlMain.getSize());
        pnlMain.add(check_Customer_Stats);
        pnlMain.repaint();
        pnlMain.revalidate();
    }
}
