/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.water.client.views;

import edu.ijse.water.client.controller.ManageCustomerController;
import edu.ijse.water.dto.CustomerDTO;
import edu.ijse.water.observer.Observer;
import java.awt.Color;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SL_WOLF
 */
public class Entrance extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form AddCategory
     */
    int cid;
    public Entrance() {
        initComponents();
        cid=0;
        setTime();
        setDate();
        
        try {
            UnicastRemoteObject.exportObject(this, 0);
            ManageCustomerController.getSubject().registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(Entrance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCancel = new javax.swing.JLabel();
        lblNew = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblBoxHeader = new javax.swing.JLabel();
        lblWB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        txtWBandID = new javax.swing.JTextField();
        lblBox = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(832, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCancel.setBackground(new java.awt.Color(153, 0, 0));
        lblCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCancel.setForeground(new java.awt.Color(255, 255, 255));
        lblCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancel.setText("Cancel");
        lblCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancel.setOpaque(true);
        lblCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelMouseExited(evt);
            }
        });
        add(lblCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 60, 20));

        lblNew.setBackground(new java.awt.Color(153, 0, 0));
        lblNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNew.setForeground(new java.awt.Color(255, 255, 255));
        lblNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNew.setText("Clear");
        lblNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNew.setOpaque(true);
        lblNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewMouseExited(evt);
            }
        });
        add(lblNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 60, 20));

        lblRegister.setBackground(new java.awt.Color(153, 0, 0));
        lblRegister.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setText("Register");
        lblRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegister.setOpaque(true);
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegisterMouseExited(evt);
            }
        });
        add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 80, 20));

        lblBoxHeader.setBackground(new java.awt.Color(0, 102, 153));
        lblBoxHeader.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBoxHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblBoxHeader.setText("    Register a Customer");
        lblBoxHeader.setOpaque(true);
        add(lblBoxHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 790, 30));

        lblWB.setText("Wrist Band ID                         :");
        add(lblWB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel2.setText("Date                                       :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, 20));

        txtDate.setEditable(false);
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 210, -1));

        jLabel1.setText("Time                                       :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 150, 20));

        txtTime.setEditable(false);
        add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 210, -1));
        add(txtWBandID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 210, -1));

        lblBox.setBackground(new java.awt.Color(51, 0, 0));
        lblBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 790, 390));

        lblBackground.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground.setOpaque(true);
        add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseEntered
        lblRegister.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_lblRegisterMouseEntered

    private void lblRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseExited
        lblRegister.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_lblRegisterMouseExited

    private void lblCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseExited
        lblCancel.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_lblCancelMouseExited

    private void lblCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseEntered
        lblCancel.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_lblCancelMouseEntered

    private void lblNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewMouseExited
        lblNew.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_lblNewMouseExited

    private void lblNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewMouseEntered
        lblNew.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_lblNewMouseEntered

    private void lblNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewMouseClicked
         setTime();
         txtWBandID.setText("");
    }//GEN-LAST:event_lblNewMouseClicked

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        CustomerDTO customerDTO = new CustomerDTO();
        customerDTO.setCid(cid);
        customerDTO.setWbid(txtWBandID.getText());
        customerDTO.setDate(txtDate.getText());
        customerDTO.setTime(txtTime.getText());
        
        boolean result=false;
        
        try {
            result=ManageCustomerController.addCustomer(customerDTO);
            if(result){
                JOptionPane.showMessageDialog(this, "Customer has been registered successfully");
                setTime();
                txtWBandID.setText("");
            }else{
                JOptionPane.showMessageDialog(this, "Failed to register the Customer");
                setTime();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to register the Customer", "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Entrance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblRegisterMouseClicked

    private void lblCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseClicked
         setTime();
         txtWBandID.setText("");
    }//GEN-LAST:event_lblCancelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBox;
    private javax.swing.JLabel lblBoxHeader;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblWB;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtWBandID;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        
    }

    private void setTime() {
        java.util.Date d1=new java.util.Date();
		SimpleDateFormat df=new SimpleDateFormat("HH:mm");
		String formatDate=df.format(d1);
		txtTime.setText(formatDate);
    }

    private void setDate() {
        java.util.Date d1=new java.util.Date();
		SimpleDateFormat df=new SimpleDateFormat("YYYY-MM-dd");
		String formatDate=df.format(d1);
		txtDate.setText(formatDate);
    }
}
