package edu.ijse.water.client.views;



import static com.sun.webkit.perf.WCFontPerfLogger.log;
import edu.ijse.water.client.controller.ManageCategoryController;
import edu.ijse.water.client.controller.ManageServiceController;
import edu.ijse.water.dto.CategoryDTO;
import edu.ijse.water.dto.ServiceDTO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SL_WOLF
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private int count=0;
    String catName;
    String Password;
    String serviceName;
    String serviceId;
    private Timer tmrTime;
    public Login() {
        initComponents();
        lblPowerPanel.setVisible(false);
        lblShutdown.setVisible(false);
        lblRestart.setVisible(false);
        pswLogin.setVisible(true);
        btnLogin.setVisible(true);
        loadCategories();
        dateAndTime();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        pswLogin = new javax.swing.JPasswordField();
        lblPowered = new javax.swing.JLabel();
        lbPower = new javax.swing.JLabel();
        lblShutdown = new javax.swing.JLabel();
        lblRestart = new javax.swing.JLabel();
        lblPowerPanel = new javax.swing.JLabel();
        lblPleasewait = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        cmbService = new javax.swing.JComboBox<>();
        lblPassPic = new javax.swing.JLabel();
        lblUp1 = new javax.swing.JLabel();
        lblUp = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(51, 0, 255));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 130, 40));

        pswLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pswLogin.setToolTipText("Password");
        jPanel1.add(pswLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 310, 40));

        lblPowered.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblPowered.setForeground(new java.awt.Color(255, 255, 255));
        lblPowered.setText("POWERED BY INSTITUTE OF JAVA AND SOFTWARE ENGINEERING");
        jPanel1.add(lblPowered, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 730, 440, 20));

        lbPower.setBackground(new java.awt.Color(0, 0, 0));
        lbPower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/client/assets/Iconia_50(0)_64.png"))); // NOI18N
        lbPower.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPowerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPowerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPowerMouseExited(evt);
            }
        });
        jPanel1.add(lbPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 710, 70, 40));

        lblShutdown.setBackground(new java.awt.Color(102, 102, 102));
        lblShutdown.setForeground(new java.awt.Color(255, 255, 255));
        lblShutdown.setText("    Shut down");
        lblShutdown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShutdown.setOpaque(true);
        lblShutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShutdownMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblShutdownMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblShutdownMouseExited(evt);
            }
        });
        jPanel1.add(lblShutdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 630, 150, 30));

        lblRestart.setBackground(new java.awt.Color(102, 102, 102));
        lblRestart.setForeground(new java.awt.Color(255, 255, 255));
        lblRestart.setText("    Restart");
        lblRestart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRestart.setOpaque(true);
        lblRestart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRestartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRestartMouseExited(evt);
            }
        });
        jPanel1.add(lblRestart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 670, 150, 30));

        lblPowerPanel.setBackground(new java.awt.Color(102, 102, 102));
        lblPowerPanel.setOpaque(true);
        lblPowerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPowerPanelMouseExited(evt);
            }
        });
        jPanel1.add(lblPowerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 630, 150, 70));

        lblPleasewait.setBackground(new java.awt.Color(204, 204, 204));
        lblPleasewait.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPleasewait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPleasewait.setText("Select The Service And Enter the Service Password");
        lblPleasewait.setOpaque(true);
        jPanel1.add(lblPleasewait, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 440, 40));

        cmbCategory.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        cmbCategory.setMaximumRowCount(100);
        cmbCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoryItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 300, 40));

        cmbService.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        cmbService.setMaximumRowCount(100);
        cmbService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbService.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbService.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbServiceItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbService, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 300, 40));

        lblPassPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/client/assets/Entypo_d83d(0)_48_1.png"))); // NOI18N
        jPanel1.add(lblPassPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 50, 40));

        lblUp1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblUp1.setForeground(new java.awt.Color(255, 255, 255));
        lblUp1.setText("Let's Get Started.....");
        jPanel1.add(lblUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 370, 70));

        lblUp.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblUp.setForeground(new java.awt.Color(255, 255, 255));
        lblUp.setText("Welcome");
        jPanel1.add(lblUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 70));

        lblTime.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 200, 70));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/client/assets/bridge-wallpapers-1.jpg"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbPowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPowerMouseClicked
        if(count==0){
            lblPowerPanel.setVisible(true);
            lblShutdown.setVisible(true);
            lblRestart.setVisible(true);
            count=1;
        }else{
            lblPowerPanel.setVisible(false);
            lblShutdown.setVisible(false);
            lblRestart.setVisible(false);
            count=0; 
        }
        
    }//GEN-LAST:event_lbPowerMouseClicked

    private void lblShutdownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShutdownMouseEntered
        lblShutdown.setBackground(Color.GRAY);
    }//GEN-LAST:event_lblShutdownMouseEntered

    private void lblShutdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShutdownMouseClicked

        pswLogin.setVisible(false);
        btnLogin.setVisible(false);
        
        
     
        try {
            lblPleasewait.setVisible(true);
            lblPleasewait.setText("Shuting Down");
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        tmrTime.stop();
        this.dispose();
        
    }//GEN-LAST:event_lblShutdownMouseClicked
  

    private void lbPowerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPowerMouseEntered
       lblPowered.setBackground(new Color(102,102,102));
  
       
    }//GEN-LAST:event_lbPowerMouseEntered
 
    private void lbPowerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPowerMouseExited
       
    }//GEN-LAST:event_lbPowerMouseExited

    private void lblPowerPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPowerPanelMouseExited
       
    }//GEN-LAST:event_lblPowerPanelMouseExited

    private void lblRestartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestartMouseEntered
        lblRestart.setBackground(Color.GRAY);
    }//GEN-LAST:event_lblRestartMouseEntered

    private void lblRestartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestartMouseExited
        lblRestart.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_lblRestartMouseExited

    private void lblShutdownMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShutdownMouseExited
         lblShutdown.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_lblShutdownMouseExited

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
       serviceName = cmbService.getSelectedItem().toString();
       set();
       
       if(Password.matches(pswLogin.getText())){
             new HomePage(serviceId,serviceName).setVisible(true);
             this.dispose();
       }else{
            Wrong();
       }
       
    }//GEN-LAST:event_btnLoginMouseClicked

    private void cmbCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoryItemStateChanged
        catName=cmbCategory.getSelectedItem().toString();
        loadServices();
    }//GEN-LAST:event_cmbCategoryItemStateChanged

    private void cmbServiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbServiceItemStateChanged
       
    }//GEN-LAST:event_cmbServiceItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbService;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPower;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblPassPic;
    private javax.swing.JLabel lblPleasewait;
    private javax.swing.JLabel lblPowerPanel;
    private javax.swing.JLabel lblPowered;
    private javax.swing.JLabel lblRestart;
    private javax.swing.JLabel lblShutdown;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUp;
    private javax.swing.JLabel lblUp1;
    private javax.swing.JPasswordField pswLogin;
    // End of variables declaration//GEN-END:variables

    private void loadCategories() {
        String name;
        try {
            List<CategoryDTO> categoryDTOs = ManageCategoryController.getAllCategories();

            if (categoryDTOs == null) {
                return;
            }

            for (CategoryDTO categoryDTO : categoryDTOs) {
                
                name=categoryDTO.getCatName();
                cmbCategory.addItem(name);
            }


        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadServices() {
        cmbService.removeAllItems();
        try {
            List<ServiceDTO> serviceDTOs = ManageServiceController.getAllServices();

            if (serviceDTOs == null) {
                return;
            }

            for (ServiceDTO serviceDTO : serviceDTOs) {
                CategoryDTO categoryDTO=serviceDTO.getCategoryDTO();
                    if(catName.matches(categoryDTO.getCatName())){
                        cmbService.addItem(serviceDTO.getServiceName());
                    }
            }

        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void set() {
        try {
            List<ServiceDTO> serviceDTOs = ManageServiceController.getAllServices();

            if (serviceDTOs == null) {
                return;
            }

            for (ServiceDTO serviceDTO : serviceDTOs) {
                    if(serviceName.matches(serviceDTO.getServiceName())){
                        Password=serviceDTO.getPassword();
                        serviceId=serviceDTO.getServiceId();
                    }
            }

        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void dateAndTime() {
        tmrTime=new Timer(0, new ActionListener() {

           
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh: mm: ss");
                lblTime.setText(sdf.format(dt));
            }

        } );
         tmrTime.start();
    }

    private void Wrong() {
        lblPleasewait.setText("Password dose not Mathch");
        lblPleasewait.setForeground(Color.red);
        lblPleasewait.setBackground(Color.white);
    }
}
