/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.water.client.views;

import java.awt.Color;
import java.text.SimpleDateFormat;

/**
 *
 * @author SL_WOLF
 */
public class Place_Order extends javax.swing.JPanel {

    /**
     * Creates new form ManageCategory
     */
    private String serviceId;
    private String serviceName;
    public Place_Order() {
        initComponents();
        Load();
    }

    Place_Order(String serviceId, String serviceName) {
        initComponents();
        this.serviceId=serviceId;
        this.serviceName=serviceName;
        Load();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUpLine = new javax.swing.JLabel();
        lblBar = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(846, 639));
        setMinimumSize(new java.awt.Dimension(846, 639));
        setPreferredSize(new java.awt.Dimension(846, 639));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUpLine.setBackground(new java.awt.Color(255, 102, 51));
        lblUpLine.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUpLine.setForeground(new java.awt.Color(255, 255, 255));
        lblUpLine.setText("  ");
        lblUpLine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblUpLine.setOpaque(true);
        lblUpLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpLineMouseClicked(evt);
            }
        });
        add(lblUpLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        lblBar.setBackground(new java.awt.Color(255, 102, 51));
        lblBar.setOpaque(true);
        add(lblBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 580));
    }// </editor-fold>//GEN-END:initComponents
        
    private void lblUpLineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpLineMouseClicked
        
    }//GEN-LAST:event_lblUpLineMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBar;
    private javax.swing.JLabel lblUpLine;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    private void Load() {
        lblUpLine.setForeground(Color.BLACK);
        lblUpLine.setBackground(Color.WHITE);
        
        if(serviceId.matches("service001")){
            lblUpLine.setText("     +  Register");
            pnlMain.setVisible(true);
            Entrance a = new Entrance();
            pnlMain.removeAll();
            a.setSize(pnlMain.getSize());
            pnlMain.add(a);
            pnlMain.repaint();
            pnlMain.revalidate();
       }else if(serviceId.matches("service002")){
            lblUpLine.setText("     +  Checkout");
            pnlMain.setVisible(true);
            CheckOut a = new CheckOut();
            pnlMain.removeAll();
            a.setSize(pnlMain.getSize());
            pnlMain.add(a);
            pnlMain.repaint();
            pnlMain.revalidate();
       }else if(serviceId.matches("service003") | serviceId.matches("service004")){
            lblUpLine.setText("     +  Place Order");
            pnlMain.setVisible(true);
            Place_Order_Shop a= new Place_Order_Shop(serviceId);
            pnlMain.removeAll();
            a.setSize(pnlMain.getSize());
            pnlMain.add(a);
            pnlMain.repaint();
            pnlMain.revalidate();
       }else{
            lblUpLine.setText("     +  Place Order");
            pnlMain.setVisible(true);
            Place_Order_Common a= new Place_Order_Common(serviceId);
            pnlMain.removeAll();
            a.setSize(pnlMain.getSize());
            pnlMain.add(a);
            pnlMain.repaint();
            pnlMain.revalidate();
       }

        
    }

   
}
