/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.water.views;

import java.awt.Color;

/**
 *
 * @author SL_WOLF
 */
public class Customer_Reports extends javax.swing.JPanel {

    /**
     * Creates new form Customer_Reports
     */
    public Customer_Reports() {
        initComponents();
        Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCustReportMain = new javax.swing.JPanel();
        lblReport = new javax.swing.JLabel();
        lblBar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(846, 639));
        setMinimumSize(new java.awt.Dimension(846, 639));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCustReportMain.setBackground(new java.awt.Color(255, 255, 255));
        add(pnlCustReportMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 580));

        lblReport.setBackground(new java.awt.Color(255, 102, 51));
        lblReport.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblReport.setForeground(new java.awt.Color(255, 255, 255));
        lblReport.setText("     +  Customer Reports ");
        lblReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReport.setOpaque(true);
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
        });
        add(lblReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        lblBar.setBackground(new java.awt.Color(255, 102, 51));
        lblBar.setOpaque(true);
        add(lblBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked
        lblReport.setForeground(Color.BLACK);
        lblReport.setBackground(Color.WHITE);
        

//        pnlCategoryMain.setVisible(true);
//        Category_List category_List= new Category_List();
//        pnlCategoryMain.removeAll();
//        category_List.setSize(pnlCategoryMain.getSize());
//        pnlCategoryMain.add(category_List);
//        pnlCategoryMain.repaint();
//        pnlCategoryMain.revalidate();
    }//GEN-LAST:event_lblReportMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBar;
    private javax.swing.JLabel lblReport;
    private javax.swing.JPanel pnlCustReportMain;
    // End of variables declaration//GEN-END:variables

    private void Load() {
        lblReport.setBackground(Color.WHITE);
       lblReport.setForeground(Color.BLACK);
        
      
     
        pnlCustReportMain.setVisible(true);
        Customer_Report customer_Report = new Customer_Report();
        pnlCustReportMain.removeAll();
        customer_Report.setSize(pnlCustReportMain.getSize());
        pnlCustReportMain.add(customer_Report);
        pnlCustReportMain.repaint();
        pnlCustReportMain.revalidate();
    }
}
