/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.water.views;

import java.awt.Color;

/**
 *
 * @author SL_WOLF
 */
public class Daily_Report extends javax.swing.JPanel {

    /**
     * Creates new form Daily_Report
     */
    public Daily_Report() {
        initComponents();
        Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDailyMain = new javax.swing.JPanel();
        lblIncome = new javax.swing.JLabel();
        lblBar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(846, 639));
        setMinimumSize(new java.awt.Dimension(846, 639));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDailyMain.setBackground(new java.awt.Color(255, 255, 255));
        add(pnlDailyMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 580));

        lblIncome.setBackground(new java.awt.Color(255, 102, 51));
        lblIncome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIncome.setForeground(new java.awt.Color(255, 255, 255));
        lblIncome.setText("     +  Daily Income Report ");
        lblIncome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIncome.setOpaque(true);
        lblIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIncomeMouseClicked(evt);
            }
        });
        add(lblIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        lblBar.setBackground(new java.awt.Color(255, 102, 51));
        lblBar.setOpaque(true);
        add(lblBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void lblIncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIncomeMouseClicked
       lblIncome.setBackground(Color.WHITE);
       lblIncome.setForeground(Color.BLACK);
        
      
     
        pnlDailyMain.setVisible(true);
        Income_Report income_Report= new Income_Report();
        pnlDailyMain.removeAll();
        income_Report.setSize(pnlDailyMain.getSize());
        pnlDailyMain.add(income_Report);
        pnlDailyMain.repaint();
        pnlDailyMain.revalidate();
    }//GEN-LAST:event_lblIncomeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBar;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JPanel pnlDailyMain;
    // End of variables declaration//GEN-END:variables

    private void Load() {
        lblIncome.setBackground(Color.WHITE);
        lblIncome.setForeground(Color.BLACK);
        
      
     
        pnlDailyMain.setVisible(true);
        Income_Report income_Report= new Income_Report();
        pnlDailyMain.removeAll();
        income_Report.setSize(pnlDailyMain.getSize());
        pnlDailyMain.add(income_Report);
        pnlDailyMain.repaint();
        pnlDailyMain.revalidate();
    }
}
