package edu.ijse.water.views;



import edu.ijse.water.controller.ManageFoodController;
import edu.ijse.water.controller.ManageIDController;
import edu.ijse.water.dto.FoodDTO;
import edu.ijse.water.dto.IDDTO;
import edu.ijse.water.observer.Observer;
import java.awt.Color;
import java.rmi.server.UnicastRemoteObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SL_WOLF
 */
public class Food_Add extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form Add_Lecturer
     */
    Border defaultBorder;
    int priceBorder;
    int descBorder;
    public Food_Add() {
        initComponents();
        defaultBorder = txtDesc.getBorder();
        priceBorder = 0;
        descBorder = 0;
        lblAdd.setVisible(false);
        loadID();
        
        try {
            UnicastRemoteObject.exportObject(this, 0);
            ManageFoodController.getSubject().registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(Food_Add.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBoxHeader = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new org.jdesktop.swingx.JXTextField();
        lblDesc = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new org.jdesktop.swingx.JXTextField();
        lblAdd = new javax.swing.JLabel();
        lblClear = new javax.swing.JLabel();
        lblCancel = new javax.swing.JLabel();
        lblBox = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBoxHeader.setBackground(new java.awt.Color(0, 102, 153));
        lblBoxHeader.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBoxHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblBoxHeader.setText("    Add New Item");
        lblBoxHeader.setOpaque(true);
        add(lblBoxHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 790, 30));

        lblId.setText("Item ID                                     :");
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        txtId.setEditable(false);
        txtId.setPrompt("f001");
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 210, -1));

        lblDesc.setText("Description                               :");
        add(lblDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescKeyTyped(evt);
            }
        });
        add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 210, -1));

        lblPrice.setText("Price                                         :");
        add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtPrice.setPrompt("xx.xx");
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPriceKeyPressed(evt);
            }
        });
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 210, -1));

        lblAdd.setBackground(new java.awt.Color(153, 0, 0));
        lblAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdd.setText("Add");
        lblAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAdd.setOpaque(true);
        lblAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddMouseExited(evt);
            }
        });
        add(lblAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 60, 20));

        lblClear.setBackground(new java.awt.Color(153, 0, 0));
        lblClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblClear.setForeground(new java.awt.Color(255, 255, 255));
        lblClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClear.setText("Clear");
        lblClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClear.setOpaque(true);
        lblClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClearMouseExited(evt);
            }
        });
        add(lblClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 60, 20));

        lblCancel.setBackground(new java.awt.Color(153, 0, 0));
        lblCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCancel.setForeground(new java.awt.Color(255, 255, 255));
        lblCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancel.setText("Cancel");
        lblCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancel.setOpaque(true);
        lblCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelMouseExited(evt);
            }
        });
        add(lblCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 60, 20));

        lblBox.setBackground(new java.awt.Color(51, 0, 0));
        lblBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 790, 390));

        lblBackground.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground.setOpaque(true);
        add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void lblClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseEntered
        lblClear.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_lblClearMouseEntered

    private void lblAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseEntered
        lblAdd.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_lblAddMouseEntered

    private void lblCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseEntered
        lblCancel.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_lblCancelMouseEntered

    private void lblClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseExited
        lblClear.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_lblClearMouseExited

    private void lblAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseExited
        lblAdd.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_lblAddMouseExited

    private void lblCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseExited
        lblCancel.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_lblCancelMouseExited

    private void lblAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseClicked
        FoodDTO foodDTO = new FoodDTO();
        foodDTO.setFid(txtId.getText());
        foodDTO.setDescription(txtDesc.getText());
        foodDTO.setPrice(Double.parseDouble(txtPrice.getText()));
        
            
            boolean result;
        
            try {
                result=ManageFoodController.addFood(foodDTO);
                if(result){
                    JOptionPane.showMessageDialog(this, "Item has been saved successfully");
                    clear();
                }else{
                    JOptionPane.showMessageDialog(this, "Failed to save the Item");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Failed to save the Item", "Error", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Food_Add.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_lblAddMouseClicked

    private void lblClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseClicked
        clear();
    }//GEN-LAST:event_lblClearMouseClicked
         
    private void txtDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyTyped
        if(txtDesc.getText().matches("[A-Za-z ]+")){
            txtDesc.setBorder(defaultBorder);
            descBorder=1;
            check();
        }else{
            txtDesc.setBorder(BorderFactory.createLineBorder(Color.red));
            descBorder=0;
            check();
        }
    }//GEN-LAST:event_txtDescKeyTyped

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed

    }//GEN-LAST:event_txtIdKeyPressed

    private void txtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyPressed
        if(txtPrice.getText().matches("[0-9]+.[0-9]+")){
            txtPrice.setBorder(defaultBorder);
            priceBorder=1;
            check();
        }else{
            txtPrice.setBorder(BorderFactory.createLineBorder(Color.red));
            priceBorder=0;
            check();
        }
    }//GEN-LAST:event_txtPriceKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBox;
    private javax.swing.JLabel lblBoxHeader;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblClear;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JTextField txtDesc;
    private org.jdesktop.swingx.JXTextField txtId;
    private org.jdesktop.swingx.JXTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        
    }

    private void check() {
            if(descBorder>0){
                if(descBorder>0){
                    lblAdd.setVisible(true);
                }else{
                    lblAdd.setVisible(false);
                }
            }else{
                lblAdd.setVisible(false);
            }
    }

    private void loadID() {
        IDDTO idDTO=new IDDTO("Food", "fid");
        try {
            String id=ManageIDController.getNewID(idDTO, "f");
            txtId.setText(id);
        } catch (Exception ex) {
            Logger.getLogger(Food_Add.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clear() {
        txtId.setText("");
        txtId.setBorder(defaultBorder);
        txtDesc.setText("");
        txtDesc.setBorder(defaultBorder);
        txtPrice.setText("");
        txtPrice.setBorder(defaultBorder);
        lblAdd.setVisible(false);
        priceBorder = 0;
        descBorder = 0;
        loadID();
    }
}
