package edu.ijse.water.views;



import edu.ijse.water.controller.ManageGiftController;
import edu.ijse.water.dto.GiftDTO;
import edu.ijse.water.observer.Observer;
import java.awt.Color;
import java.rmi.server.UnicastRemoteObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SL_WOLF
 */
public class Gift_Update extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form Update_student
     */
     private String reservedGid = "";
     private boolean update = false;
    Border defaultBorder;
    int valid;
    public Gift_Update() {
        initComponents();
        defaultBorder = txtDesc.getBorder();
       valid=0;
        lblUpdate.setVisible(false);
        
        try {
            UnicastRemoteObject.exportObject(this, 0);
            ManageGiftController.getSubject().registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(Gift_Update.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBoxHeader = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new org.jdesktop.swingx.JXTextField();
        txtDesc = new javax.swing.JTextField();
        txtPrice = new org.jdesktop.swingx.JXTextField();
        lblDesc = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();
        lblNew = new javax.swing.JLabel();
        lblCancel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBox = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBoxHeader.setBackground(new java.awt.Color(0, 102, 153));
        lblBoxHeader.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBoxHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblBoxHeader.setText("   Update Item Details");
        lblBoxHeader.setOpaque(true);
        add(lblBoxHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 790, 30));

        lblId.setText("Item ID                                     :");
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        txtId.setPrompt("g001");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 210, -1));

        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });
        txtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescKeyTyped(evt);
            }
        });
        add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 210, -1));

        txtPrice.setPrompt("xx.xx");
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPriceKeyPressed(evt);
            }
        });
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 210, -1));

        lblDesc.setText("Description                                :");
        add(lblDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lblPrice.setText("Price                                         :");
        add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblUpdate.setBackground(new java.awt.Color(153, 0, 0));
        lblUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate.setText("Update");
        lblUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUpdate.setOpaque(true);
        lblUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUpdateMouseExited(evt);
            }
        });
        add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 60, 20));

        lblNew.setBackground(new java.awt.Color(153, 0, 0));
        lblNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNew.setForeground(new java.awt.Color(255, 255, 255));
        lblNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNew.setText("Clear");
        lblNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNew.setOpaque(true);
        lblNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewMouseExited(evt);
            }
        });
        add(lblNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 60, 20));

        lblCancel.setBackground(new java.awt.Color(153, 0, 0));
        lblCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCancel.setForeground(new java.awt.Color(255, 255, 255));
        lblCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancel.setText("Cancel");
        lblCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancel.setOpaque(true);
        lblCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelMouseExited(evt);
            }
        });
        add(lblCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/Entypo_d83d(0)_32_1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, 20));

        lblBox.setBackground(new java.awt.Color(51, 0, 0));
        lblBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 790, 390));

        lblBackground.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground.setText(" ");
        lblBackground.setOpaque(true);
        add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed

    private void lblUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseClicked
       GiftDTO giftDTO = new GiftDTO();
        giftDTO.setGid(txtId.getText());
        giftDTO.setDescription(txtDesc.getText());
        giftDTO.setPrice(Double.parseDouble(txtPrice.getText()));
        
        
            boolean result=false;
        
            try {
                result=ManageGiftController.updateGift(giftDTO);
                if(result){
                    JOptionPane.showMessageDialog(this, "Item has been Update successfully");
                }else{
                    JOptionPane.showMessageDialog(this, "Failed to Update the Item");
                }
                ManageGiftController.releaseGift(reservedGid);
                reservedGid = "";
                txtId.requestFocusInWindow();
                update = false;
                txtId.setText("");
                txtId.setBorder(defaultBorder);
                txtDesc.setText("");
                txtDesc.setBorder(defaultBorder);
                txtPrice.setText("");
                txtPrice.setBorder(defaultBorder);
                lblUpdate.setVisible(false);
                valid=0;
                
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Failed to Update the Item", "Error", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Gift_Update.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_lblUpdateMouseClicked

    private void lblUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseEntered
        lblUpdate.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_lblUpdateMouseEntered

    private void lblUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseExited
        lblUpdate.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_lblUpdateMouseExited

    private void lblNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewMouseEntered
        lblNew.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_lblNewMouseEntered

    private void lblNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewMouseExited
        lblNew.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_lblNewMouseExited

    private void lblCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseEntered
        lblCancel.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_lblCancelMouseEntered

    private void lblCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseExited
        lblCancel.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_lblCancelMouseExited

    private void lblNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewMouseClicked
        txtId.setText("");
        txtId.setBorder(defaultBorder);
        txtDesc.setText("");
        txtDesc.setBorder(defaultBorder);
        txtPrice.setText("");
        txtPrice.setBorder(defaultBorder);
        lblUpdate.setVisible(false);
        valid=0;
    }//GEN-LAST:event_lblNewMouseClicked

    private void txtDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyTyped
        if(txtDesc.getText().matches("[A-Za-z ]+")){
            txtDesc.setBorder(defaultBorder);
            valid=0;
            check();
        }else{
            txtDesc.setBorder(BorderFactory.createLineBorder(Color.red));
            valid=1;
            check();
        }
    }//GEN-LAST:event_txtDescKeyTyped

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        if(txtId.getText().matches("g[0-9]+")){
            txtId.setBorder(defaultBorder);
        }else{
            txtId.setBorder(BorderFactory.createLineBorder(Color.red));
        }
    }//GEN-LAST:event_txtIdKeyPressed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        lblUpdate.setVisible(true);
        GiftDTO giftDTO = new GiftDTO();
        
         try {
             giftDTO=ManageGiftController.searchGift(txtId.getText());
             
             if(giftDTO!= null){
                 
             }else{
                 JOptionPane.showMessageDialog(this,"Check The  ID Again");
             }
             
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "No data found...", "Error", JOptionPane.ERROR_MESSAGE); 
             Logger.getLogger(Category_Remove.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        try {
                    if (reservedGid == "") {
                        ManageGiftController.releaseGift(reservedGid);
                    }
                    reservedGid = txtId.getText();
                    boolean reserveCategory = ManageGiftController.reserveGift(reservedGid);

                    if (reserveCategory) {
                        update = true;
                        txtDesc.setText(giftDTO.getDescription());
                        txtPrice.setText(""+giftDTO.getPrice());
                    } else {
                        update = false;
                        JOptionPane.showMessageDialog(Gift_Update.this, "Item has been already reserved");
                    }

                } catch (Exception ex) {
                    Logger.getLogger(Gift_Update.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyPressed
        if(txtPrice.getText().matches("[0-9]+.[0-9]+")){
            txtPrice.setBorder(defaultBorder);
            valid=0;
            check();
        }else{
            txtPrice.setBorder(BorderFactory.createLineBorder(Color.red));
            valid=1;
            check();
        }
    }//GEN-LAST:event_txtPriceKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBox;
    private javax.swing.JLabel lblBoxHeader;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JTextField txtDesc;
    private org.jdesktop.swingx.JXTextField txtId;
    private org.jdesktop.swingx.JXTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        
    }

    private void check() {
        if(valid>0){
            lblUpdate.setVisible(false);
        }else{
            lblUpdate.setVisible(true);
        }
    }
}
