package edu.ijse.water.views;



import edu.ijse.water.controller.ManageMessageController;
import edu.ijse.water.dto.MessagesDTO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SL_WOLF
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
   
    private int count3=0;
    private int count2=0;
    private JLabel x;
    private int count=0;
    private Timer tmrTime;
    public HomePage() {
        initComponents();
        Load();
    }

    HomePage(String userName) {
        initComponents();
        Load();
        lblNotiUserName.setText(userName);
        setTimeAndDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblReportsDaily = new javax.swing.JLabel();
        lblCustomerReports = new javax.swing.JLabel();
        lblReportsBox = new javax.swing.JLabel();
        lblShopBoxGift = new javax.swing.JLabel();
        lblShopBoxFood = new javax.swing.JLabel();
        lblShopBox = new javax.swing.JLabel();
        lblDashboardline = new javax.swing.JLabel();
        lblShopLine = new javax.swing.JLabel();
        lblReportsLine = new javax.swing.JLabel();
        lblUserLine = new javax.swing.JLabel();
        lblServiceLine = new javax.swing.JLabel();
        lblCategoryLine = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblAdminLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblBar = new javax.swing.JLabel();
        lblSignIn = new javax.swing.JLabel();
        lblSignInLogo = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblLogoutLogo = new javax.swing.JLabel();
        lblBox = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        lblShops = new javax.swing.JLabel();
        lblReports = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblService = new javax.swing.JLabel();
        lblCategories = new javax.swing.JLabel();
        lblMenuBox = new javax.swing.JLabel();
        PanelMain = new javax.swing.JPanel();
        lblMenuName = new javax.swing.JLabel();
        panelNotification = new javax.swing.JPanel();
        lblNotiUser = new javax.swing.JLabel();
        lblNotiUserName = new javax.swing.JLabel();
        lblCreate = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        lblNotiInUserName = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        lblNotiIn = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblServerIcon = new javax.swing.JLabel();
        lblTimeDate = new javax.swing.JLabel();
        lblNotificationBox = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBottomBar = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReportsDaily.setBackground(new java.awt.Color(51, 51, 51));
        lblReportsDaily.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblReportsDaily.setForeground(new java.awt.Color(204, 204, 204));
        lblReportsDaily.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportsDaily.setText("Daily Reports");
        lblReportsDaily.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReportsDaily.setOpaque(true);
        lblReportsDaily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportsDailyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportsDailyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportsDailyMouseExited(evt);
            }
        });
        jPanel1.add(lblReportsDaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 150, 40));

        lblCustomerReports.setBackground(new java.awt.Color(51, 51, 51));
        lblCustomerReports.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCustomerReports.setForeground(new java.awt.Color(204, 204, 204));
        lblCustomerReports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerReports.setText("Customer Reports");
        lblCustomerReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCustomerReports.setOpaque(true);
        lblCustomerReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCustomerReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCustomerReportsMouseExited(evt);
            }
        });
        jPanel1.add(lblCustomerReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 150, 40));

        lblReportsBox.setBackground(new java.awt.Color(51, 51, 51));
        lblReportsBox.setOpaque(true);
        jPanel1.add(lblReportsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 150, 80));

        lblShopBoxGift.setBackground(new java.awt.Color(51, 51, 51));
        lblShopBoxGift.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblShopBoxGift.setForeground(new java.awt.Color(204, 204, 204));
        lblShopBoxGift.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShopBoxGift.setText("Gift Shop");
        lblShopBoxGift.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShopBoxGift.setOpaque(true);
        lblShopBoxGift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShopBoxGiftMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblShopBoxGiftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblShopBoxGiftMouseExited(evt);
            }
        });
        jPanel1.add(lblShopBoxGift, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 110, 40));

        lblShopBoxFood.setBackground(new java.awt.Color(51, 51, 51));
        lblShopBoxFood.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblShopBoxFood.setForeground(new java.awt.Color(204, 204, 204));
        lblShopBoxFood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShopBoxFood.setText("Food Stores");
        lblShopBoxFood.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShopBoxFood.setOpaque(true);
        lblShopBoxFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShopBoxFoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblShopBoxFoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblShopBoxFoodMouseExited(evt);
            }
        });
        jPanel1.add(lblShopBoxFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 110, 40));

        lblShopBox.setBackground(new java.awt.Color(51, 51, 51));
        lblShopBox.setOpaque(true);
        jPanel1.add(lblShopBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 110, 80));

        lblDashboardline.setBackground(new java.awt.Color(51, 51, 51));
        lblDashboardline.setOpaque(true);
        jPanel1.add(lblDashboardline, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 10, 40));

        lblShopLine.setBackground(new java.awt.Color(51, 51, 51));
        lblShopLine.setOpaque(true);
        jPanel1.add(lblShopLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 10, 40));

        lblReportsLine.setBackground(new java.awt.Color(51, 51, 51));
        lblReportsLine.setOpaque(true);
        jPanel1.add(lblReportsLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 10, 40));

        lblUserLine.setBackground(new java.awt.Color(51, 51, 51));
        lblUserLine.setOpaque(true);
        jPanel1.add(lblUserLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 10, 40));

        lblServiceLine.setBackground(new java.awt.Color(51, 51, 51));
        lblServiceLine.setOpaque(true);
        jPanel1.add(lblServiceLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 10, 40));

        lblCategoryLine.setBackground(new java.awt.Color(51, 51, 51));
        lblCategoryLine.setOpaque(true);
        jPanel1.add(lblCategoryLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 10, 40));

        lblAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lblAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAdmin.setText(" Admin ");
        lblAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdminMouseExited(evt);
            }
        });
        jPanel1.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 70, 30));

        lblAdminLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblAdminLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/Entypo_d83d(0)_32.png"))); // NOI18N
        lblAdminLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdminLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdminLogoMouseExited(evt);
            }
        });
        jPanel1.add(lblAdminLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 30, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/waterworld-.png"))); // NOI18N
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 220, 40));

        lblBar.setBackground(new java.awt.Color(255, 0, 0));
        lblBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/Nr11 (482).jpg"))); // NOI18N
        jPanel1.add(lblBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        lblSignIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSignIn.setText("Sign in");
        lblSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignIn.setOpaque(true);
        lblSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSignInMouseExited(evt);
            }
        });
        jPanel1.add(lblSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 60, 100, 30));

        lblSignInLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/Entypo_d83d(0)_24.png"))); // NOI18N
        lblSignInLogo.setOpaque(true);
        jPanel1.add(lblSignInLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 60, 30, 30));

        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLogout.setText("    Log out");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });
        jPanel1.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, 110, 30));

        lblLogoutLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoutLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/Iconia_50(0)_48.png"))); // NOI18N
        lblLogoutLogo.setOpaque(true);
        jPanel1.add(lblLogoutLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 100, 20, 30));

        lblBox.setOpaque(true);
        jPanel1.add(lblBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 60, 130, 70));

        lblDashboard.setBackground(new java.awt.Color(39, 58, 77));
        lblDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(204, 204, 204));
        lblDashboard.setText("    +   Dash board");
        lblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDashboard.setOpaque(true);
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDashboardMouseExited(evt);
            }
        });
        jPanel1.add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 40));

        lblShops.setBackground(new java.awt.Color(39, 58, 77));
        lblShops.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblShops.setForeground(new java.awt.Color(204, 204, 204));
        lblShops.setText("    +   Manage Shops");
        lblShops.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShops.setOpaque(true);
        lblShops.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShopsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblShopsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblShopsMouseExited(evt);
            }
        });
        jPanel1.add(lblShops, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 40));

        lblReports.setBackground(new java.awt.Color(39, 58, 77));
        lblReports.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblReports.setForeground(new java.awt.Color(204, 204, 204));
        lblReports.setText("    +   Reports         ");
        lblReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReports.setOpaque(true);
        lblReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportsMouseExited(evt);
            }
        });
        jPanel1.add(lblReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 240, 40));

        lblUser.setBackground(new java.awt.Color(39, 58, 77));
        lblUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setText("    +   Manage Users ");
        lblUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUser.setOpaque(true);
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserMouseExited(evt);
            }
        });
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 240, 40));

        lblService.setBackground(new java.awt.Color(39, 58, 77));
        lblService.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblService.setForeground(new java.awt.Color(204, 204, 204));
        lblService.setText("    +   Manage Services");
        lblService.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblService.setOpaque(true);
        lblService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblServiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblServiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblServiceMouseExited(evt);
            }
        });
        jPanel1.add(lblService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 40));

        lblCategories.setBackground(new java.awt.Color(39, 58, 77));
        lblCategories.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCategories.setForeground(new java.awt.Color(204, 204, 204));
        lblCategories.setText("    +   Manage Categories");
        lblCategories.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCategories.setOpaque(true);
        lblCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCategoriesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCategoriesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCategoriesMouseExited(evt);
            }
        });
        jPanel1.add(lblCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 40));

        lblMenuBox.setBackground(new java.awt.Color(39, 58, 77));
        lblMenuBox.setOpaque(true);
        jPanel1.add(lblMenuBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 580));

        PanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(PanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 890, 630));

        lblMenuName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMenuName.setForeground(new java.awt.Color(102, 102, 102));
        lblMenuName.setText("Admin Dashboard");
        jPanel1.add(lblMenuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        panelNotification.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNotiUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNotiUser.setForeground(new java.awt.Color(204, 204, 204));
        lblNotiUser.setText("Logged Admin");
        panelNotification.add(lblNotiUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblNotiUserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNotiUserName.setForeground(new java.awt.Color(204, 204, 204));
        lblNotiUserName.setText("Malindu Dilshan");
        panelNotification.add(lblNotiUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCreate.setText(" Send Messages To Employees");
        panelNotification.add(lblCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, 30));
        panelNotification.add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 220, 30));

        lblNotiInUserName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNotiInUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblNotiInUserName.setText("Messages That alredy sended");
        panelNotification.add(lblNotiInUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmPassword.setText("Type your Message");
        panelNotification.add(lblConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 120, -1));

        btnSend.setBackground(new java.awt.Color(204, 51, 0));
        btnSend.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSend.setText("SEND");
        btnSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendMouseClicked(evt);
            }
        });
        panelNotification.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 100, -1));

        btnClear.setBackground(new java.awt.Color(0, 153, 51));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panelNotification.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 100, -1));

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        panelNotification.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 220, 170));

        lblNotiIn.setBackground(new java.awt.Color(102, 102, 102));
        lblNotiIn.setOpaque(true);
        panelNotification.add(lblNotiIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 235, 360));

        lblTime.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelNotification.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 220, 40));

        lblDate.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelNotification.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 220, 40));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Servers Up");
        panelNotification.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 80, 20));

        lblServerIcon.setBackground(new java.awt.Color(255, 255, 255));
        lblServerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/Green_Arrow_Top 20 20.png"))); // NOI18N
        lblServerIcon.setOpaque(true);
        panelNotification.add(lblServerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 20, 20));

        lblTimeDate.setBackground(new java.awt.Color(102, 102, 102));
        lblTimeDate.setText(" ");
        lblTimeDate.setOpaque(true);
        panelNotification.add(lblTimeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 235, 70));

        lblNotificationBox.setBackground(new java.awt.Color(39, 58, 77));
        lblNotificationBox.setOpaque(true);
        panelNotification.add(lblNotificationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 630));

        jLabel1.setText("jLabel1");
        panelNotification.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 750, -1, -1));

        jPanel1.add(panelNotification, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 100, 240, 630));

        lblBottomBar.setBackground(new java.awt.Color(0, 0, 0));
        lblBottomBar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblBottomBar.setForeground(new java.awt.Color(255, 255, 255));
        lblBottomBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBottomBar.setText("POWERED BY INSTITUTE OF JAVA AND SOFTWARE ENGINEERING");
        lblBottomBar.setOpaque(true);
        jPanel1.add(lblBottomBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1370, 40));

        lblBackground.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground.setOpaque(true);
        lblBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackgroundMouseClicked(evt);
            }
        });
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAdminLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminLogoMouseEntered
        lblAdmin.setBackground(new Color(240,240,240));
        lblAdmin.setForeground(Color.BLACK);
        lblAdminLogo.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_lblAdminLogoMouseEntered

    private void lblAdminLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminLogoMouseExited
        lblAdmin.setBackground( Color.WHITE);
        lblAdmin.setForeground(Color.BLACK);
        lblAdminLogo.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblAdminLogoMouseExited

    private void lblSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseEntered
        lblSignIn.setBackground(new Color(102,102,255));
        lblSignInLogo.setBackground(new Color(102,102,255));
        lblSignIn.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblSignInMouseEntered

    private void lblSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseExited
        lblSignIn.setBackground(new Color(240,240,240));
        lblSignInLogo.setBackground(new Color(240,240,240));
        lblSignIn.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblSignInMouseExited

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setBackground(new Color(102,102,255));
        lblLogoutLogo.setBackground(new Color(102,102,255));
        lblLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setBackground(new Color(240,240,240));
        lblLogoutLogo.setBackground(new Color(240,240,240));
        lblLogout.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
         int res = JOptionPane.showConfirmDialog(this, " Do You Want To Log out ? " );
         if(res==0){
             new Login().setVisible(true);
             tmrTime.stop();
             this.dispose();
             
         }

        
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseClicked
        if(count==0){
            lblBox.setVisible(true);
            lblSignInLogo.setVisible(true);
            lblSignIn.setVisible(true);
            lblLogoutLogo.setVisible(true);
            lblLogout.setVisible(true);
            count=1;
        }else{
           lblBox.setVisible(false);
            lblSignInLogo.setVisible(false);
            lblSignIn.setVisible(false);
            lblLogoutLogo.setVisible(false);
            lblLogout.setVisible(false);
            count=0;
        }
    }//GEN-LAST:event_lblAdminMouseClicked

    private void lblAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseEntered
        lblAdmin.setBackground(new Color(240,240,240));
        lblAdmin.setForeground(Color.BLACK);
        lblAdminLogo.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_lblAdminMouseEntered

    private void lblAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseExited
       lblAdmin.setBackground( Color.WHITE);
        lblAdmin.setForeground(Color.BLACK);
        lblAdminLogo.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblAdminMouseExited

    private void lblAdminLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminLogoMouseClicked
        if(count==0){
            lblBox.setVisible(true);
            lblSignInLogo.setVisible(true);
            lblSignIn.setVisible(true);
            lblLogoutLogo.setVisible(true);
            lblLogout.setVisible(true);
            count=1;
        }else{
           lblBox.setVisible(false);
            lblSignInLogo.setVisible(false);
            lblSignIn.setVisible(false);
            lblLogoutLogo.setVisible(false);
            lblLogout.setVisible(false);
            count=0;
        }
    }//GEN-LAST:event_lblAdminLogoMouseClicked

    private void lblDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseEntered
       
        lblDashboard.setForeground(Color.WHITE);
        lblDashboardline.setVisible(true);
       
    }//GEN-LAST:event_lblDashboardMouseEntered

    private void lblDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseExited
  
        lblDashboard.setForeground(new Color(204,204,204));
        lblDashboardline.setVisible(false);
    }//GEN-LAST:event_lblDashboardMouseExited

    private void lblShopsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShopsMouseEntered
        
        lblShops.setForeground(Color.WHITE);
        lblShopLine.setVisible(true);
    }//GEN-LAST:event_lblShopsMouseEntered

    private void lblShopsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShopsMouseExited
        lblShops.setForeground(new Color(204,204,204));
        lblShopLine.setVisible(false);
    }//GEN-LAST:event_lblShopsMouseExited

    private void lblReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseEntered
        lblReports.setForeground(Color.WHITE);
        lblReportsLine.setVisible(true);
    }//GEN-LAST:event_lblReportsMouseEntered

    private void lblReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseExited
         lblReports.setForeground(new Color(204,204,204));
         lblReportsLine.setVisible(false);
    }//GEN-LAST:event_lblReportsMouseExited

    private void lblUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseEntered
        lblUser.setForeground(Color.WHITE);
        lblUserLine.setVisible(true);
    }//GEN-LAST:event_lblUserMouseEntered

    private void lblUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseExited
        lblUser.setForeground(new Color(204,204,204));
        lblUserLine.setVisible(false);
    }//GEN-LAST:event_lblUserMouseExited

    private void lblServiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServiceMouseEntered
        lblService.setForeground(Color.WHITE);
        lblServiceLine.setVisible(true);
    }//GEN-LAST:event_lblServiceMouseEntered

    private void lblServiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServiceMouseExited
        lblService.setForeground(new Color(204,204,204));
        lblServiceLine.setVisible(false);
    }//GEN-LAST:event_lblServiceMouseExited

    private void lblCategoriesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCategoriesMouseEntered
        lblCategories.setForeground(Color.WHITE);
        lblCategoryLine.setVisible(true);
    }//GEN-LAST:event_lblCategoriesMouseEntered

    private void lblCategoriesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCategoriesMouseExited
        lblCategories.setForeground(new Color(204,204,204));
        lblCategoryLine.setVisible(false);
    }//GEN-LAST:event_lblCategoriesMouseExited

    private void lblShopsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShopsMouseClicked
        x.setBackground(new Color(39,58,77));
        lblShops.setBackground(new Color(51,51,51));
        x=lblShops;
        if(count2==0){
            lblShopBoxGift.setVisible(true);
            lblShopBoxFood.setVisible(true);
            lblShopBox.setVisible(true);
            count2=1;
        }else{
            lblShopBoxGift.setVisible(false);
            lblShopBoxFood.setVisible(false);
            lblShopBox.setVisible(false);
            count2=0;
        }
         lblReportsBox.setVisible(false);
        lblReportsDaily.setVisible(false);
        lblCustomerReports.setVisible(false);
        count3=0;
        
    }//GEN-LAST:event_lblShopsMouseClicked

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        x.setBackground(new Color(39,58,77));
        lblDashboard.setBackground(new Color(51,51,51));
        x=lblDashboard;
        lblShopBoxGift.setVisible(false);
        lblShopBoxFood.setVisible(false);
        lblShopBox.setVisible(false);
        lblReportsBox.setVisible(false);
        lblReportsDaily.setVisible(false);
        lblCustomerReports.setVisible(false);
        count2=0;
        count3=0;
        
        lblMenuName.setText("Admin Dashboard");
        panelNotification.setVisible(true);
        PanelMain.setVisible(false);
        
        PanelMain.setVisible(true);
        Dashboard d=new Dashboard();
        PanelMain.removeAll();
        d.setSize(PanelMain.getSize());
        PanelMain.add(d);
        PanelMain.repaint();
        PanelMain.revalidate();
        
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseClicked
         x.setBackground(new Color(39,58,77));
        lblReports.setBackground(new Color(51,51,51));
        x=lblReports;
        lblShopBoxGift.setVisible(false);
        lblShopBoxFood.setVisible(false);
        lblShopBox.setVisible(false);
        if(count3==0){
            lblReportsBox.setVisible(true);
            lblReportsDaily.setVisible(true);
            lblCustomerReports.setVisible(true);
            count3=1;
        }else{
            lblReportsBox.setVisible(false);
            lblReportsDaily.setVisible(false);
            lblCustomerReports.setVisible(false);
            count3=0;
        }
        count2=0;
        
    }//GEN-LAST:event_lblReportsMouseClicked

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        x.setBackground(new Color(39,58,77));
        lblUser.setBackground(new Color(51,51,51));
        x=lblUser;
        lblShopBoxGift.setVisible(false);
        lblShopBoxFood.setVisible(false);
        lblShopBox.setVisible(false);
        lblReportsBox.setVisible(false);
        lblReportsDaily.setVisible(false);
        lblCustomerReports.setVisible(false);
        count2=0;
        count3=0;
        
        lblShopLine.setVisible(false);
        
        lblMenuName.setText("Manage Users");
        PanelMain.setVisible(true);
        Manage_User manage_User= new Manage_User();
        PanelMain.removeAll();
        manage_User.setSize(PanelMain.getSize());
        PanelMain.add(manage_User);
        PanelMain.repaint();
        PanelMain.revalidate();
       
    }//GEN-LAST:event_lblUserMouseClicked

    private void lblServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServiceMouseClicked
        x.setBackground(new Color(39,58,77));
        lblService.setBackground(new Color(51,51,51));
        x=lblService;
        lblShopBoxGift.setVisible(false);
        lblShopBoxFood.setVisible(false);
        lblShopBox.setVisible(false);
        lblReportsBox.setVisible(false);
        lblReportsDaily.setVisible(false);
        lblCustomerReports.setVisible(false);
        count2=0;
        count3=0;
        
        lblMenuName.setText("Manage Services");
        PanelMain.setVisible(true);
        Manage_Services manage_Services = new Manage_Services();
        PanelMain.removeAll();
        manage_Services.setSize(PanelMain.getSize());
        PanelMain.add(manage_Services);
        PanelMain.repaint();
        PanelMain.revalidate();
     
    }//GEN-LAST:event_lblServiceMouseClicked

    private void lblCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCategoriesMouseClicked
        lblCategoryLine.setVisible(true);
        x.setBackground(new Color(39,58,77));
        lblCategories.setBackground(new Color(51,51,51));
        x=lblCategories;
        lblShopBoxGift.setVisible(false);
        lblShopBoxFood.setVisible(false);
        lblShopBox.setVisible(false);
        lblReportsBox.setVisible(false);
        lblReportsDaily.setVisible(false);
        lblCustomerReports.setVisible(false);
        
        count2=0;
        count3=0;
        lblShopLine.setVisible(false);
        
        lblMenuName.setText("Manage Categories");
        PanelMain.setVisible(true);
        Manage_Category manage_Category = new Manage_Category();
        PanelMain.removeAll();
        manage_Category.setSize(PanelMain.getSize());
        PanelMain.add(manage_Category);
        PanelMain.repaint();
        PanelMain.revalidate();
        
    }//GEN-LAST:event_lblCategoriesMouseClicked

    private void lblShopBoxGiftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShopBoxGiftMouseEntered
        lblShopBoxGift.setForeground(Color.WHITE);
        lblShopBoxGift.setBackground(new Color(102,102,102));
        lblShopLine.setVisible(true);
    }//GEN-LAST:event_lblShopBoxGiftMouseEntered

    private void lblShopBoxGiftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShopBoxGiftMouseExited
        lblShopBoxGift.setForeground(new Color(204,204,204));
        lblShopBoxGift.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_lblShopBoxGiftMouseExited

    private void lblShopBoxFoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShopBoxFoodMouseEntered
        lblShopBoxFood.setForeground(Color.WHITE);
        lblShopBoxFood.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_lblShopBoxFoodMouseEntered

    private void lblShopBoxFoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShopBoxFoodMouseExited
        lblShopBoxFood.setForeground(new Color(204,204,204));
        lblShopBoxFood.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_lblShopBoxFoodMouseExited

    private void lblShopBoxGiftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShopBoxGiftMouseClicked
        lblShopBoxGift.setVisible(false);
        lblShopBoxFood.setVisible(false);
        lblShopBox.setVisible(false);
        count2=0;
        count3=0;
        lblShopLine.setVisible(false);
        
        lblMenuName.setText("Manage Gift Shop");
        PanelMain.setVisible(true);
        Manage_Gift_Shop a=new Manage_Gift_Shop();
        PanelMain.removeAll();
        a.setSize(PanelMain.getSize());
        PanelMain.add(a);
        PanelMain.repaint();
        PanelMain.revalidate();
       
        
    }//GEN-LAST:event_lblShopBoxGiftMouseClicked

    private void lblShopBoxFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShopBoxFoodMouseClicked
       lblShopBoxGift.setVisible(false);
        lblShopBoxFood.setVisible(false);
        lblShopBox.setVisible(false);
        count2=0;
        count3=0;
        lblShopLine.setVisible(false);
        
        lblMenuName.setText("Manage Food Store Details");
        PanelMain.setVisible(true);
        Manage_Food_Shop a=new Manage_Food_Shop();
        PanelMain.removeAll();
        a.setSize(PanelMain.getSize());
        PanelMain.add(a);
        PanelMain.repaint();
        PanelMain.revalidate();
    }//GEN-LAST:event_lblShopBoxFoodMouseClicked

    private void lblBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMouseClicked
        lblShopBoxGift.setVisible(false);
        lblShopBoxFood.setVisible(false);
        lblShopBox.setVisible(false);
        lblReportsBox.setVisible(false);
        lblReportsDaily.setVisible(false);
        lblCustomerReports.setVisible(false);
        count2=0;
        count3=0;
        lblBox.setVisible(false);
        lblSignInLogo.setVisible(false);
        lblSignIn.setVisible(false);
        lblLogoutLogo.setVisible(false);
        lblLogout.setVisible(false);
        count=0;
    }//GEN-LAST:event_lblBackgroundMouseClicked

    private void lblReportsDailyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsDailyMouseEntered
        lblReportsDaily.setForeground(Color.WHITE);
        lblReportsDaily.setBackground(new Color(102,102,102));
        lblReportsLine.setVisible(true);
    }//GEN-LAST:event_lblReportsDailyMouseEntered

    private void lblReportsDailyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsDailyMouseExited
        lblReportsDaily.setForeground(new Color(204,204,204));
        lblReportsDaily.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_lblReportsDailyMouseExited

    private void lblCustomerReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerReportsMouseEntered
        lblCustomerReports.setForeground(Color.WHITE);
        lblCustomerReports.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_lblCustomerReportsMouseEntered

    private void lblCustomerReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerReportsMouseExited
        lblCustomerReports.setForeground(new Color(204,204,204));
        lblCustomerReports.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_lblCustomerReportsMouseExited

    private void lblReportsDailyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsDailyMouseClicked
        lblReportsBox.setVisible(false);
        lblReportsDaily.setVisible(false);
        lblCustomerReports.setVisible(false);
        count2=0;
        count3=0;
        lblReportsLine.setVisible(false);
        PanelMain.setVisible(false);
        lblMenuName.setText("Daily Reports"); 
        PanelMain.setVisible(true);
        Daily_Report daily_Report = new Daily_Report();
        PanelMain.removeAll();
        daily_Report.setSize(PanelMain.getSize());
        PanelMain.add(daily_Report);
        PanelMain.repaint();
        PanelMain.revalidate();
       
        
        
        

    }//GEN-LAST:event_lblReportsDailyMouseClicked

    private void lblCustomerReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerReportsMouseClicked
        lblReportsBox.setVisible(false);
        lblReportsDaily.setVisible(false);
        lblCustomerReports.setVisible(false);
        count2=0;
        count3=0;
        lblReportsLine.setVisible(false);
        
        PanelMain.setVisible(false);
        lblMenuName.setText("Customers Reports"); 
        PanelMain.setVisible(true);
        Customer_Reports customer_Reports= new Customer_Reports();
        PanelMain.removeAll();
        customer_Reports.setSize(PanelMain.getSize());
        PanelMain.add(customer_Reports);
        PanelMain.repaint();
        PanelMain.revalidate();
    }//GEN-LAST:event_lblCustomerReportsMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
       txtType.setText(null);
       txtType.requestFocus();
       
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseClicked
       MessagesDTO messagesDTO= new MessagesDTO();
       messagesDTO.setMid(0);
       messagesDTO.setMessage(txtType.getText());
       messagesDTO.setDate(lblDate.getText());
        
        try {
            boolean result=ManageMessageController.addMessage(messagesDTO);
            if(result){
                txtArea.append(txtType.getText()+"\n");
                txtType.setText("");
                txtType.requestFocus();
            }
        } catch (Exception ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSendMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAdminLogo;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBar;
    private javax.swing.JLabel lblBottomBar;
    private javax.swing.JLabel lblBox;
    private javax.swing.JLabel lblCategories;
    private javax.swing.JLabel lblCategoryLine;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblCustomerReports;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDashboardline;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblLogoutLogo;
    private javax.swing.JLabel lblMenuBox;
    private javax.swing.JLabel lblMenuName;
    private javax.swing.JLabel lblNotiIn;
    private javax.swing.JLabel lblNotiInUserName;
    private javax.swing.JLabel lblNotiUser;
    private javax.swing.JLabel lblNotiUserName;
    private javax.swing.JLabel lblNotificationBox;
    private javax.swing.JLabel lblReports;
    private javax.swing.JLabel lblReportsBox;
    private javax.swing.JLabel lblReportsDaily;
    private javax.swing.JLabel lblReportsLine;
    private javax.swing.JLabel lblServerIcon;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblServiceLine;
    private javax.swing.JLabel lblShopBox;
    private javax.swing.JLabel lblShopBoxFood;
    private javax.swing.JLabel lblShopBoxGift;
    private javax.swing.JLabel lblShopLine;
    private javax.swing.JLabel lblShops;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JLabel lblSignInLogo;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeDate;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserLine;
    private javax.swing.JPanel panelNotification;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables

    private void Load() {
        lblBox.setBackground(new Color(240,240,240));
        lblSignInLogo.setBackground(new Color(240,240,240));
        lblSignIn.setBackground(new Color(240,240,240));
        lblLogoutLogo.setBackground(new Color(240,240,240));
        lblLogout.setBackground(new Color(240,240,240));
        lblBox.setVisible(false);
        lblSignInLogo.setVisible(false);
        lblSignIn.setVisible(false);
        lblLogoutLogo.setVisible(false);
        lblLogout.setVisible(false);
        lblShopBoxGift.setVisible(false);
        lblShopBoxFood.setVisible(false);
        lblShopBox.setVisible(false);
        lblDashboard.setBackground(new Color(51,51,51));
        x=lblDashboard;
        lblReportsBox.setVisible(false);
        lblReportsDaily.setVisible(false);
        lblCustomerReports.setVisible(false);
        lblDashboardline.setVisible(false);
        lblShopLine.setVisible(false);
        lblReportsLine.setVisible(false);
        lblUserLine.setVisible(false);
        lblServiceLine.setVisible(false);
        lblCategoryLine.setVisible(false);
        
        
        PanelMain.setVisible(true);
        Dashboard d=new Dashboard();
        PanelMain.removeAll();
        d.setSize(PanelMain.getSize());
        PanelMain.add(d);
        PanelMain.repaint();
        PanelMain.revalidate();
    }

    private void setTimeAndDate() {
        
        java.util.Date d1=new java.util.Date();
		SimpleDateFormat df=new SimpleDateFormat("YYYY-MM-dd");
		String formatDate=df.format(d1);
		lblDate.setText(formatDate);
        
        
        tmrTime=new Timer(0, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh: mm: ss");
                lblTime.setText(sdf.format(dt));
            }

        } );
         tmrTime.start();
    }
}
