/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.water.views;

import edu.ijse.water.controller.ManagePaymentController;
import edu.ijse.water.dto.PaymentDTO;
import edu.ijse.water.jasper.MyJasperView;
import edu.ijse.water.observer.Observer;
import java.awt.Color;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.util.JRLoader;


/**
 *
 * @author SL_WOLF
 */
public class Income_Report extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form Income_Report
     */
    private double total;
    String day;
    public Income_Report() {
        initComponents();
        total=0;
        day="";
        
        try {
            UnicastRemoteObject.exportObject(this, 0);
            ManagePaymentController.getSubject().registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(Income_Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBoxHeader = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblPrint = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayments = new javax.swing.JTable();
        lblSearch = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dChooser = new com.toedter.calendar.JDateChooser();
        lblBox = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(832, 520));
        setMinimumSize(new java.awt.Dimension(832, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBoxHeader.setBackground(new java.awt.Color(0, 102, 153));
        lblBoxHeader.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBoxHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblBoxHeader.setText("    Enter The Date");
        lblBoxHeader.setOpaque(true);
        add(lblBoxHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 790, 30));

        lblDate.setText("Total Daily Income                            :");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 180, 20));

        lblDate1.setText("Date                              :");
        add(lblDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 120, 20));

        txtTotal.setEditable(false);
        add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 200, -1));

        lblPrint.setBackground(new java.awt.Color(153, 0, 0));
        lblPrint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPrint.setForeground(new java.awt.Color(255, 255, 255));
        lblPrint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrint.setText("Print the report");
        lblPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPrint.setOpaque(true);
        lblPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPrintMouseExited(evt);
            }
        });
        add(lblPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 110, 20));

        tblPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Payment Id", "Payment Type", "Payment Details", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPayments);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 750, 330));

        lblSearch.setBackground(new java.awt.Color(0, 102, 102));
        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/Entypo_d83d(0)_32_1.png"))); // NOI18N
        lblSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
        });
        add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 90, 20));

        jLabel2.setBackground(new java.awt.Color(0, 153, 102));
        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 60, 20));
        add(dChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 220, -1));

        lblBox.setBackground(new java.awt.Color(51, 0, 0));
        lblBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 790, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void lblPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintMouseEntered
        lblPrint.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_lblPrintMouseEntered

    private void lblPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintMouseExited
        lblPrint.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_lblPrintMouseExited

    private void lblPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintMouseClicked
        try {
            JasperReport compiledReport=(JasperReport) JRLoader.loadObject(Income_Report.class.getResource("/edu/ijse/water/jasper/Income.jasper"));
            
            HashMap<String,Object> parameters = new HashMap<>();
            parameters.put("Date", day);
            parameters.put("Total", txtTotal.getText());
            JasperPrint filledReport=JasperFillManager.fillReport(compiledReport, parameters, new JRTableModelDataSource(tblPayments.getModel()));
            
            MyJasperView frmJasperView=new MyJasperView(filledReport);
            frmJasperView.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Income_Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblPrintMouseClicked

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
           Date date = dChooser.getDate();
           SimpleDateFormat simpleDateFormat = new SimpleDateFormat("YYYY-MM-DD");
           day=simpleDateFormat.format(date);
           
           
        DefaultTableModel dtm = (DefaultTableModel) tblPayments.getModel();
        dtm.setRowCount(0);
        total=0;

        try {
            List<PaymentDTO> paymentDTOs = ManagePaymentController.getPayment(day);

            if (paymentDTOs == null) {
                return;
            }

            for (PaymentDTO paymentDTO : paymentDTOs) {
                
                total=total+paymentDTO.getAmount();
                txtTotal.setText(""+total);
                
                Object[] rowData = {
                    paymentDTO.getOid(),
                    paymentDTO.getPid(),
                    paymentDTO.getPaymentType(),
                    paymentDTO.getPaymentDetails(),
                    paymentDTO.getAmount()
                };
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No data found...", "Error", JOptionPane.ERROR_MESSAGE); 
            Logger.getLogger(Food_List.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblSearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBox;
    private javax.swing.JLabel lblBoxHeader;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblPrint;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblPayments;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        
    }
}
