package edu.ijse.water.views;



import edu.ijse.water.controller.ManageUserController;
import edu.ijse.water.dto.UserDTO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SL_WOLF
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private int count=0;
    List<UserDTO> userDTOs;
    private Timer tmrTime;
   
    
    public Login() {
        initComponents();
        load();
        dateAndTime();
        lblPowerPanel.setVisible(false);
        lblShutdown.setVisible(false);
        lblRestart.setVisible(false);
        txtUsername.setVisible(true);
        pswPass.setVisible(true);
        btnLogin.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        pswPass = new javax.swing.JPasswordField();
        lblPowered = new javax.swing.JLabel();
        lbPower = new javax.swing.JLabel();
        lblShutdown = new javax.swing.JLabel();
        lblRestart = new javax.swing.JLabel();
        lblPowerPanel = new javax.swing.JLabel();
        lblPleasewait = new javax.swing.JLabel();
        lblUsernamePic = new javax.swing.JLabel();
        lblPassPic = new javax.swing.JLabel();
        lblUp1 = new javax.swing.JLabel();
        lblUp = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setToolTipText("User Name");
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 320, 40));

        btnLogin.setBackground(new java.awt.Color(51, 0, 255));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 130, 40));

        pswPass.setToolTipText("Password");
        jPanel1.add(pswPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 310, 40));

        lblPowered.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblPowered.setForeground(new java.awt.Color(255, 255, 255));
        lblPowered.setText("POWERED BY INSTITUTE OF JAVA AND SOFTWARE ENGINEERING");
        jPanel1.add(lblPowered, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 730, 440, 20));

        lbPower.setBackground(new java.awt.Color(0, 0, 0));
        lbPower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/Iconia_50(0)_64.png"))); // NOI18N
        lbPower.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPowerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPowerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPowerMouseExited(evt);
            }
        });
        jPanel1.add(lbPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 710, 70, 40));

        lblShutdown.setBackground(new java.awt.Color(102, 102, 102));
        lblShutdown.setForeground(new java.awt.Color(255, 255, 255));
        lblShutdown.setText("    Shut down");
        lblShutdown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShutdown.setOpaque(true);
        lblShutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShutdownMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblShutdownMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblShutdownMouseExited(evt);
            }
        });
        jPanel1.add(lblShutdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 630, 150, 30));

        lblRestart.setBackground(new java.awt.Color(102, 102, 102));
        lblRestart.setForeground(new java.awt.Color(255, 255, 255));
        lblRestart.setText("    Restart");
        lblRestart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRestart.setOpaque(true);
        lblRestart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRestartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRestartMouseExited(evt);
            }
        });
        jPanel1.add(lblRestart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 670, 150, 30));

        lblPowerPanel.setBackground(new java.awt.Color(102, 102, 102));
        lblPowerPanel.setOpaque(true);
        lblPowerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPowerPanelMouseExited(evt);
            }
        });
        jPanel1.add(lblPowerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 630, 150, 70));

        lblPleasewait.setBackground(new java.awt.Color(204, 204, 204));
        lblPleasewait.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPleasewait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPleasewait.setText("Enter Your UserName And Password");
        lblPleasewait.setOpaque(true);
        jPanel1.add(lblPleasewait, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 440, 40));

        lblUsernamePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/Entypo_d83d(0)_48.png"))); // NOI18N
        jPanel1.add(lblUsernamePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 50, 40));

        lblPassPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/Entypo_d83d(0)_48_1.png"))); // NOI18N
        jPanel1.add(lblPassPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 50, 40));

        lblUp1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblUp1.setForeground(new java.awt.Color(255, 255, 255));
        lblUp1.setText("Let's Get Started.....");
        jPanel1.add(lblUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 370, 70));

        lblUp.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblUp.setForeground(new java.awt.Color(255, 255, 255));
        lblUp.setText("Welcome");
        jPanel1.add(lblUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 70));

        lblTime.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 200, 70));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/water/assets/bridge-wallpapers-1.jpg"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbPowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPowerMouseClicked
        if(count==0){
            lblPowerPanel.setVisible(true);
            lblShutdown.setVisible(true);
            lblRestart.setVisible(true);
            count=1;
        }else{
            lblPowerPanel.setVisible(false);
            lblShutdown.setVisible(false);
            lblRestart.setVisible(false);
            count=0; 
        }
        
    }//GEN-LAST:event_lbPowerMouseClicked

    private void lblShutdownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShutdownMouseEntered
        lblShutdown.setBackground(Color.GRAY);
    }//GEN-LAST:event_lblShutdownMouseEntered

    private void lblShutdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShutdownMouseClicked
        txtUsername.setVisible(false);
        pswPass.setVisible(false);
        btnLogin.setVisible(false);
        lblPleasewait.setText("Sutting Down.....");
        tmrTime.stop();
        
     
        try {
            
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        
    }//GEN-LAST:event_lblShutdownMouseClicked
  

    private void lbPowerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPowerMouseEntered
       lblPowered.setBackground(new Color(102,102,102));
  
       
    }//GEN-LAST:event_lbPowerMouseEntered
 
    private void lbPowerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPowerMouseExited
       
    }//GEN-LAST:event_lbPowerMouseExited

    private void lblPowerPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPowerPanelMouseExited
       
    }//GEN-LAST:event_lblPowerPanelMouseExited

    private void lblRestartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestartMouseEntered
        lblRestart.setBackground(Color.GRAY);
    }//GEN-LAST:event_lblRestartMouseEntered

    private void lblRestartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestartMouseExited
        lblRestart.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_lblRestartMouseExited

    private void lblShutdownMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShutdownMouseExited
         lblShutdown.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_lblShutdownMouseExited

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        String userName=txtUsername.getText();
        String password=pswPass.getText();
        
        for (UserDTO userDTO : userDTOs) {
                if(userDTO.getUserName().matches(userName)){
                    if(userDTO.getPassword().matches(password)){
                        new HomePage(userName).setVisible(true);
                        this.dispose();
                    }
                }else{
                    Set();
                }
            }
        
        
        
    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPower;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblPassPic;
    private javax.swing.JLabel lblPleasewait;
    private javax.swing.JLabel lblPowerPanel;
    private javax.swing.JLabel lblPowered;
    private javax.swing.JLabel lblRestart;
    private javax.swing.JLabel lblShutdown;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUp;
    private javax.swing.JLabel lblUp1;
    private javax.swing.JLabel lblUsernamePic;
    private javax.swing.JPasswordField pswPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void load() {
        try {
             userDTOs = ManageUserController.getAllUsers();

        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void Set() {
        lblPleasewait.setText("Username And Password dose not Mathch");
        lblPleasewait.setForeground(Color.red);
        lblPleasewait.setBackground(Color.white);
    }

    private void dateAndTime() {
        tmrTime=new Timer(0, new ActionListener() {

           
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh: mm: ss");
                lblTime.setText(sdf.format(dt));
            }

        } );
         tmrTime.start();
    }
}
