/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.water.views;

import java.awt.Color;

/**
 *
 * @author SL_WOLF
 */
public class Manage_User extends javax.swing.JPanel {

    /**
     * Creates new form Manage_User
     */
    public Manage_User() {
        initComponents();
        Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUpdate = new javax.swing.JLabel();
        lblRemove = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        lblList = new javax.swing.JLabel();
        lblBar = new javax.swing.JLabel();
        pnlUserMain = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(846, 639));
        setMinimumSize(new java.awt.Dimension(846, 639));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUpdate.setBackground(new java.awt.Color(255, 102, 51));
        lblUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdate.setText("   +  Update User Details");
        lblUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUpdate.setOpaque(true);
        lblUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateMouseClicked(evt);
            }
        });
        add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 150, 40));

        lblRemove.setBackground(new java.awt.Color(255, 102, 51));
        lblRemove.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRemove.setForeground(new java.awt.Color(255, 255, 255));
        lblRemove.setText("        +  Remove User");
        lblRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRemove.setOpaque(true);
        lblRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveMouseClicked(evt);
            }
        });
        add(lblRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 140, 40));

        lblAdd.setBackground(new java.awt.Color(255, 102, 51));
        lblAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setText("        +  Add User");
        lblAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAdd.setOpaque(true);
        lblAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddMouseClicked(evt);
            }
        });
        add(lblAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 120, 40));

        lblList.setBackground(new java.awt.Color(255, 102, 51));
        lblList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblList.setForeground(new java.awt.Color(255, 255, 255));
        lblList.setText("       +  Users");
        lblList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblList.setOpaque(true);
        lblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListMouseClicked(evt);
            }
        });
        add(lblList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        lblBar.setBackground(new java.awt.Color(255, 102, 51));
        lblBar.setOpaque(true);
        add(lblBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));

        pnlUserMain.setBackground(new java.awt.Color(255, 255, 255));
        add(pnlUserMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void lblUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseClicked
        lblUpdate.setBackground(Color.WHITE);
        lblUpdate.setForeground(Color.BLACK);
        lblList.setBackground(new Color(255,102,51));
        lblList.setForeground(Color.WHITE);
        lblAdd.setBackground(new Color(255,102,51));
        lblAdd.setForeground(Color.WHITE);
        lblRemove.setBackground(new Color(255,102,51));
        lblRemove.setForeground(Color.WHITE);

        pnlUserMain.setVisible(true);
        User_Update user_Update = new User_Update();
        pnlUserMain.removeAll();
        user_Update.setSize(pnlUserMain.getSize());
        pnlUserMain.add(user_Update);
        pnlUserMain.repaint();
        pnlUserMain.revalidate();
    }//GEN-LAST:event_lblUpdateMouseClicked

    private void lblRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseClicked

        lblRemove.setForeground(Color.BLACK);
        lblRemove.setBackground(Color.WHITE);
        lblAdd.setForeground(Color.WHITE);
        lblAdd.setBackground(new Color(255,102,51));
        lblList.setForeground(Color.WHITE);
        lblList.setBackground(new Color(255,102,51));
        lblUpdate.setForeground(Color.WHITE);
        lblUpdate.setBackground(new Color(255,102,51));

        pnlUserMain.setVisible(true);
        User_Remove user_Remove = new User_Remove();
        pnlUserMain.removeAll();
        user_Remove.setSize(pnlUserMain.getSize());
        pnlUserMain.add(user_Remove);
        pnlUserMain.repaint();
        pnlUserMain.revalidate();
    }//GEN-LAST:event_lblRemoveMouseClicked

    private void lblAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseClicked

        lblAdd.setForeground(Color.BLACK);
        lblAdd.setBackground(Color.WHITE);
        lblList.setForeground(Color.WHITE);
        lblList.setBackground(new Color(255,102,51));
        lblRemove.setForeground(Color.WHITE);
        lblRemove.setBackground(new Color(255,102,51));
        lblUpdate.setForeground(Color.WHITE);
        lblUpdate.setBackground(new Color(255,102,51));

        pnlUserMain.setVisible(true);
        User_Add user_Add=new User_Add();
        pnlUserMain.removeAll();
        user_Add.setSize(pnlUserMain.getSize());
        pnlUserMain.add(user_Add);
        pnlUserMain.repaint();
        pnlUserMain.revalidate();
    }//GEN-LAST:event_lblAddMouseClicked

    private void lblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListMouseClicked
        lblList.setForeground(Color.BLACK);
        lblList.setBackground(Color.WHITE);
        lblAdd.setForeground(Color.WHITE);
        lblAdd.setBackground(new Color(255,102,51));
        lblRemove.setForeground(Color.WHITE);
        lblRemove.setBackground(new Color(255,102,51));
        lblUpdate.setForeground(Color.WHITE);
        lblUpdate.setBackground(new Color(255,102,51));

        pnlUserMain.setVisible(true);
        User_List user_List = new User_List();
        pnlUserMain.removeAll();
        user_List.setSize(pnlUserMain.getSize());
        pnlUserMain.add(user_List);
        pnlUserMain.repaint();
        pnlUserMain.revalidate();
    }//GEN-LAST:event_lblListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblBar;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JPanel pnlUserMain;
    // End of variables declaration//GEN-END:variables

    private void Load() {
        lblList.setBackground(Color.WHITE);
        lblList.setForeground(Color.BLACK);
        
      
     
        pnlUserMain.setVisible(true);
        User_List user_List = new User_List();
        pnlUserMain.removeAll();
        user_List.setSize(pnlUserMain.getSize());
        pnlUserMain.add(user_List);
        pnlUserMain.repaint();
        pnlUserMain.revalidate();
    }
}
