/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.water.views;

import java.awt.Color;

/**
 *
 * @author SL_WOLF
 */
public class Manage_Services extends javax.swing.JPanel {

    /**
     * Creates new form Manage_Services
     */
    public Manage_Services() {
        initComponents();
        Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUpdate = new javax.swing.JLabel();
        lblRemove = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        lblList = new javax.swing.JLabel();
        lblBar = new javax.swing.JLabel();
        pnlServiceMain = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(846, 639));
        setMinimumSize(new java.awt.Dimension(846, 639));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUpdate.setBackground(new java.awt.Color(255, 102, 51));
        lblUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdate.setText("    +  Update Service");
        lblUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUpdate.setOpaque(true);
        lblUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateMouseClicked(evt);
            }
        });
        add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 130, 40));

        lblRemove.setBackground(new java.awt.Color(255, 102, 51));
        lblRemove.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRemove.setForeground(new java.awt.Color(255, 255, 255));
        lblRemove.setText("      +  Remove Service");
        lblRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRemove.setOpaque(true);
        lblRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveMouseClicked(evt);
            }
        });
        add(lblRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 140, 40));

        lblAdd.setBackground(new java.awt.Color(255, 102, 51));
        lblAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setText("      +  Add Service");
        lblAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAdd.setOpaque(true);
        lblAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddMouseClicked(evt);
            }
        });
        add(lblAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 120, 40));

        lblList.setBackground(new java.awt.Color(255, 102, 51));
        lblList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblList.setForeground(new java.awt.Color(255, 255, 255));
        lblList.setText("        +  Services");
        lblList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblList.setOpaque(true);
        lblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListMouseClicked(evt);
            }
        });
        add(lblList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        lblBar.setBackground(new java.awt.Color(255, 102, 51));
        lblBar.setOpaque(true);
        add(lblBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));

        pnlServiceMain.setBackground(new java.awt.Color(255, 255, 255));
        add(pnlServiceMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void lblUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseClicked
        lblUpdate.setBackground(Color.WHITE);
        lblUpdate.setForeground(Color.BLACK);
        lblList.setBackground(new Color(255,102,51));
        lblList.setForeground(Color.WHITE);
        lblAdd.setBackground(new Color(255,102,51));
        lblAdd.setForeground(Color.WHITE);
        lblRemove.setBackground(new Color(255,102,51));
        lblRemove.setForeground(Color.WHITE);

        pnlServiceMain.setVisible(true);
        Service_Update service_Update= new Service_Update();
        pnlServiceMain.removeAll();
        service_Update.setSize(pnlServiceMain.getSize());
        pnlServiceMain.add(service_Update);
        pnlServiceMain.repaint();
        pnlServiceMain.revalidate();
    }//GEN-LAST:event_lblUpdateMouseClicked

    private void lblRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseClicked

        lblRemove.setForeground(Color.BLACK);
        lblRemove.setBackground(Color.WHITE);
        lblAdd.setForeground(Color.WHITE);
        lblAdd.setBackground(new Color(255,102,51));
        lblList.setForeground(Color.WHITE);
        lblList.setBackground(new Color(255,102,51));
        lblUpdate.setForeground(Color.WHITE);
        lblUpdate.setBackground(new Color(255,102,51));

        pnlServiceMain.setVisible(true);
        Service_Remove service_Remove=new Service_Remove();
        pnlServiceMain.removeAll();
        service_Remove.setSize(pnlServiceMain.getSize());
        pnlServiceMain.add(service_Remove);
        pnlServiceMain.repaint();
        pnlServiceMain.revalidate();
    }//GEN-LAST:event_lblRemoveMouseClicked

    private void lblAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseClicked

        lblAdd.setForeground(Color.BLACK);
        lblAdd.setBackground(Color.WHITE);
        lblList.setForeground(Color.WHITE);
        lblList.setBackground(new Color(255,102,51));
        lblRemove.setForeground(Color.WHITE);
        lblRemove.setBackground(new Color(255,102,51));
        lblUpdate.setForeground(Color.WHITE);
        lblUpdate.setBackground(new Color(255,102,51));

        pnlServiceMain.setVisible(true);
        Service_Add service_Add= new Service_Add();
        pnlServiceMain.removeAll();
        service_Add.setSize(pnlServiceMain.getSize());
        pnlServiceMain.add(service_Add);
        pnlServiceMain.repaint();
        pnlServiceMain.revalidate();
    }//GEN-LAST:event_lblAddMouseClicked

    private void lblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListMouseClicked
        lblList.setForeground(Color.BLACK);
        lblList.setBackground(Color.WHITE);
        lblAdd.setForeground(Color.WHITE);
        lblAdd.setBackground(new Color(255,102,51));
        lblRemove.setForeground(Color.WHITE);
        lblRemove.setBackground(new Color(255,102,51));
        lblUpdate.setForeground(Color.WHITE);
        lblUpdate.setBackground(new Color(255,102,51));

         pnlServiceMain.setVisible(true);
        Service_List service_List= new Service_List();
        pnlServiceMain.removeAll();
        service_List.setSize(pnlServiceMain.getSize());
        pnlServiceMain.add(service_List);
        pnlServiceMain.repaint();
        pnlServiceMain.revalidate();
    }//GEN-LAST:event_lblListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblBar;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JPanel pnlServiceMain;
    // End of variables declaration//GEN-END:variables

    private void Load() {
        lblList.setBackground(Color.WHITE);
        lblList.setForeground(Color.BLACK);
        
      
     
        pnlServiceMain.setVisible(true);
        Service_List service_List= new Service_List();
        pnlServiceMain.removeAll();
        service_List.setSize(pnlServiceMain.getSize());
        pnlServiceMain.add(service_List);
        pnlServiceMain.repaint();
        pnlServiceMain.revalidate();
    }
}
